-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "eValue" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isAvailable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "weight" INTEGER NOT NULL DEFAULT 0;
