import { Container, Header } from '@/shared/components/shared';
import { getUserSession } from '@/shared/lib/get-user-session';
import type { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Скатерть-самобранка | Dashboard',
  description: 'Generated by create next app',
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getUserSession();

  if (!session || session.role !== "ADMIN") {
    redirect("/");
  }

  return (
    <main className='min-h-screen bg-white'>
      <Suspense>
      <Header hasCart={false} className="border-b-gray-200" />
      {children}
      </Suspense>
    </main>
  );
}