import { Header } from '@/shared/components';
import { getUserSession } from '@/shared/lib/get-user-session';
import { Metadata } from 'next';
import { redirect } from 'next/navigation';
import { Suspense } from 'react';
import { ReactQueryProvider } from '@/app/providers/react-query';
import AdminContainer from '../components/admin-container';

export const metadata: Metadata = {
  title: 'Скатерть-самобранка | Dashboard',
  description: 'Generated by create next app',
};

export default async function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getUserSession();

  if (!session || session.role == "USER") {
    redirect("/");
  }

  return (
    <ReactQueryProvider>
      <main className='min-h-screen bg-white'>
        <Suspense fallback={<div>Loading...</div>}>
          <Header hasCart={false} className="border-b-gray-200" />
          <AdminContainer> {/* Добавлено здесь */}
            {children}
          </AdminContainer>
        </Suspense>
      </main>
    </ReactQueryProvider>
  );
}