import { Container, Header } from '@/shared/components/shared';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Скатерть-самобранка | Оформление заказа',
  description: 'Generated by create next app',
};

export default async function CheckoutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="min-h-screen bg-[#f5f5f5]">
      <Container>
      <Header hasCart={false} className="border-b-gray-200" />
      {children}
      </Container>
    </main>
  );
}
